! This file was generated by EKAT with generate_constants.hpp and 
! generate_constants.cpp using data defined in 
!        ekat/src/ekat/physics/constants.yaml
!
!        DO NOT EDIT
!
!

module ekat_base_constants
  use iso_c_binding, only: c_double
  implicit none
  public

  integer, parameter :: c_real = c_double

! Ammonia
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_nh3 = 0.0170305_c_real
! Ammonium
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_nh4 = 0.018039_c_real
! Avogadro
!	 units: #/mol
!	 source info:
!		 name: NIST CODATA 2018

!		 url: https://physics.nist.gov/cuu/Constants/index.html

!		 citation: E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93.

real(c_real), parameter :: avogadro = 6.02214076e+23_c_real
! Boltzmann
!	 units: J/K
!	 source info:
!		 name: NIST CODATA 2018

!		 url: https://physics.nist.gov/cuu/Constants/index.html

!		 citation: E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93.

real(c_real), parameter :: boltzmann = 1.380649e-23_c_real
! Calendar_day
!	 units: s
!	 source info:
!		 name: 24 * 60 * 60

real(c_real), parameter :: calendar_day = 86400_c_real
! Carbon_atom
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_c = 0.0120107_c_real
! Carbon_dioxide
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_co2 = 0.0440095_c_real
! Carbon_monoxide
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_co = 0.0280101_c_real
! Delta_C13
!	 units: n/a
!	 source info:
!		 doi: https://doi.org/10.25844/h9q1-0p82

!		 citation: Z. Sharp, 2017, Principles of Stable Isotope Geochemistry, University of New Mexico.

real(c_real), parameter :: carbon_13_to_12_ratio = 0.011179_c_real
! Dry_air
!	 units: kg/mol
!	 source info:
!		 url: https://nvlpubs.nist.gov/nistpubs/jres/83/jresv83n5p419_a1b.pdf

!		 citation: F. E. Jones, 1978, The air density equation and the transfer of the mass unit, J. Res. National Bur. Standards 83(5).

real(c_real), parameter :: molec_weight_dry_air = 0.028963_c_real
! Dry_air_gas
!	 units: J/kg/K
!	 source info:
!		 definition: r_gas / molec_weight_dry_air

real(c_real), parameter :: rgas_dry_air = 287.072_c_real
! Earth_mean_radius
!	 units: m
!	 source info:
!		 name: NASA Space Science Data Coordinated Archive

!		 url: https://nssdc.gsfc.nasa.gov/planetary/planets/earthpage.html

real(c_real), parameter :: earth_radius = 6371000_c_real
! Earth_rotation
!	 units: 1/s
!	 source info:
!		 definition: 2*pi/sidereal_day

real(c_real), parameter :: earth_omega = 7.29211e-05_c_real
! Ice_density
!	 units: kg/mol
!	 source info:
!		 url: https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=926353

!		 citation: Harvey, A. (2019), Properties of Ice and Supercooled Water, CRC Handbook of Chemistry and Physics, CRC Press, Boca Raton, FL, [online] (Accessed May 31, 2022)

real(c_real), parameter :: density_h2o_ice_0c = 916.7_c_real
! Karman
!	 units: n/a
!	 source info:
!		 name: Journal of Fluid Mechanics

!		 citation: S. C. C. Bailey, M. Vallikivi, M. Hultmark, and A. J. Smits, 2014, Estimating the value of von Karman's constant in turbulent pipe flow, J. Fluid Mech. 749.

real(c_real), parameter :: karman = 0.4_c_real
! Latent_heat_water_evaporation
!	 units: J/kg
!	 source info:
!		 citation: R. R. Rogers and M. K. Yau, 1989, A Short Course in Cloud Physics, 3rd ed., Butterworth-Heinemann.

!		 note: Table 2.1

real(c_real), parameter :: latent_heat_evap_0c = 2501000_c_real
! Latent_heat_water_fusion
!	 units: J/kg
!	 source info:
!		 doi: https://doi.org/10.1007/1-4020-3266-8_124

!		 citation: D. R. Legates, 2005, Latent Heat, in J. E. Oliver, Encyclopedia of World Climatology, Springer.

real(c_real), parameter :: latent_heat_fusion = 333700_c_real
! Latent_heat_water_sublimation
!	 units: J/kg
!	 source info:
!		 citation: R. R. Rogers and M. K. Yau, 1989, A Short Course in Cloud Physics, 3rd ed., Butterworth-Heinemann.

!		 note: Table 2.1

real(c_real), parameter :: latent_heat_sublimation = 2834700_c_real
! Methane
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_ch4 = 0.0160425_c_real
! Nitrogen
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_n2 = 0.0280134_c_real
! Nitrogen_dioxide
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_no2 = 0.0460055_c_real
! Oxygen
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_o2 = 0.0319988_c_real
! Oxygen_atom
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_o = 0.0159994_c_real
! Ozone
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_o3 = 0.0479982_c_real
! Pi
!	 units: n/a
!	 source info:
!		 name: Mathematica 12.0.0

!		 command: N[Pi, 64]

real(c_real), parameter :: pi = 3.141592653589793_c_real
! Sidereal_day
!	 units: s
!	 source info:
!		 name: NASA Space Science Data Coordinated Archive

!		 url: https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html

real(c_real), parameter :: sidereal_day = 86164.2_c_real
! Specific_heat_dry_air_const_pressure
!	 units: J/kg/K
!	 source info:
!		 citation: C. A. Riegel and A. F. C. Bridger, 1992, Fundamentals of Atmospheric Dynamics and Thermodynamics, World Scientific.

real(c_real), parameter :: cp_dry_air = 1004.64_c_real
! Specific_heat_dry_air_const_volume
!	 units: J/kg/K
!	 source info:
!		 citation: C. A. Riegel and A. F. C. Bridger, 1992, Fundamentals of Atmospheric Dynamics and Thermodynamics, World Scientific.

real(c_real), parameter :: cv_dry_air = 717.6_c_real
! Specific_heat_ice
!	 units: J/kg/K
!	 source info:
!		 url: https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=926353

!		 citation: Harvey, A. (2019), Properties of Ice and Supercooled Water, CRC Handbook of Chemistry and Physics, CRC Press, Boca Raton, FL, [online] (Accessed May 31, 2022)

real(c_real), parameter :: cp_h2o_ice = 2110_c_real
! Specific_heat_water
!	 units: J/kg/K
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 doi: https://doi.org/10.18434/T4D303

!		 citation: E. W. Lemmon, I. H. Bell, M. L. Huber, M. O. McLinden, Thermophysical properties of fluid systems in NIST Chemistry WebBook NIST Standard Database Number 69, P. J. Linstrom and W. G. Mallard, eds.

real(c_real), parameter :: cp_h2o_liq_0c = 4219.4_c_real
! Specific_heat_water_vapor_const_pressure
!	 units: J/kg/K
!	 source info:
!		 citation: C. A. Riegel and A. F. C. Bridger, 1992, Fundamentals of Atmospheric Dynamics and Thermodynamics, World Scientific.

real(c_real), parameter :: cp_h2o_vapor = 1846_c_real
! Standard_acceleration_gravity
!	 units: m/s2
!	 source info:
!		 name: NIST CODATA 2018

!		 url: https://physics.nist.gov/cuu/Constants/index.html

!		 citation: E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93.

real(c_real), parameter :: gravity = 9.806649999999999_c_real
! Standard_atmospheric_pressure
!	 units: Pa
!	 source info:
!		 name: NIST CODATA 2018

!		 url: https://physics.nist.gov/cuu/Constants/index.html

!		 citation: E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93.

real(c_real), parameter :: standard_pressure = 100000_c_real
! Stefan_Boltzmann
!	 units: W/m2/K4
!	 source info:
!		 name: NIST CODATA 2018

!		 url: https://physics.nist.gov/cuu/Constants/index.html

!		 citation: E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93.

real(c_real), parameter :: stefan_boltzmann = 5.670374419e-08_c_real
! Sulfate
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_so4 = 0.096064_c_real
! Sulfuric_acid
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_h2so4 = 0.098078_c_real
! Surface_tension_h2o_air
!	 units: N/m
!	 source info:
!		 doi: https://doi.org/10.1063/1.4768782

!		 citation: A. Mulero, I. Cachadi\~na and M. I. Parra, 2012, Recommended correlations for the surface tension of common fluids, Journal of Chemical Reference Data, 41, 043105

real(c_real), parameter :: surface_tension_h2o_air_0c = 0.07570689080553497_c_real
! Thermal_conductivity_ice
!	 units: W/m/K
!	 source info:
!		 url: https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=926353

!		 citation: Harvey, A. (2019), Properties of Ice and Supercooled Water, CRC Handbook of Chemistry and Physics, CRC Press, Boca Raton, FL, [online] (Accessed May 31, 2022)

real(c_real), parameter :: thermal_conductivity_h2o_ice_0c = 2.1_c_real
! US_standard_atmospheric_pressure
!	 units: Pa
!	 source info:
!		 name: CRC Handbook of Physics and Chemistry Online

!		 url: https://hbcp.chemnetbase.com/faces/documents/14_12/14_12_0001.xhtml

!		 note: 1976 US Standard Atmosphere

real(c_real), parameter :: std_pressure = 101325_c_real
! Universal_gas_constant
!	 units: J/mol/K
!	 source info:
!		 name: NIST CODATA 2018

!		 url: https://physics.nist.gov/cuu/Constants/index.html

!		 citation: E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, 2021, CODATA recommended values of the fundamental physical constants: 2018, Rev. Modern Phys. 93.

real(c_real), parameter :: r_gas = 8.314462618_c_real
! VSMOW_Deuterium_ratio
!	 units: #2h/#h
!	 source info:
!		 url: https://www-s.nist.gov/m-srmors/certificates/8535.pdf

!		 citation: R. Hagemann and G. Nief and E. Roth, 1970, Absolute isotopic scale for Deuterium analysis of natural waters. Absolute D/H ratio for SMOW, Tellus 22, 712--715.

real(c_real), parameter :: vsmow_ratio_2h_h = 0.015576_c_real
! VSMOW_Oxygen17_ratio
!	 units: #17o/#16o
!	 source info:
!		 name: NIST Reference Material 8535, 2022, VSMOW Vienna Standard Mean Ocean Water

!		 url: https://www-s.nist.gov/m-srmors/certificates/8535.pdf

real(c_real), parameter :: vsmow_ratio_17o_16o = 0.03769_c_real
! VSMOW_Oxygen18_ratio
!	 units: #18o/#16o
!	 source info:
!		 name: NIST Reference Material 8535, 2022, VSMOW Vienna Standard Mean Ocean Water

!		 url: https://www-s.nist.gov/m-srmors/certificates/8535.pdf

real(c_real), parameter :: vsmow_ratio_18o_16o = 0.20052_c_real
! Water_critical_pt_temperature
!	 units: K
!	 source info:
!		 doi: https://doi.org/10.1063/1.4768782

!		 citation: A. Mulero, I. Cachadi\~na and M. I. Parra, 2012, Recommended correlations for the surface tension of common fluids, Journal of Chemical Reference Data, 41, 043105

real(c_real), parameter :: critical_temp_h2o = 647.096_c_real
! Water_density
!	 units: kg/m3
!	 source info:
!		 doi: https://doi.org/10.1088/0026-1394/38/4/3

!		 citation: M. Tanaka, G. Girard, R. Davis, A. Peuto, and N. Bignell, 2001, Recommended table for the density of water between OC and 40C based on recent experimental reports, Metrologia 38, 301.

real(c_real), parameter :: density_h2o_liq_0c = 999.8428_c_real
! Water_freeze_temperature
!	 units: K
!	 source info:
!		 url: https://doi.org/10.1063/1.555894

!		 citation: Journal of Physical and Chemical Reference Data 20, 1023 (1991).

real(c_real), parameter :: freezing_pt_h2o = 273.15_c_real
! Water_molecule
!	 units: kg/mol
!	 source info:
!		 name: NIST Chemistry WebBook SRD 69

!		 url: https://webbook.nist.gov/chemistry/

!		 doi: https://doi.org/10.18434/T4D303

real(c_real), parameter :: molec_weight_h2o = 0.0180153_c_real
! Water_triple_pt_temperature
!	 units: K
!	 source info:
!		 url: https://doi.org/10.1063/1.555894

!		 citation: Journal of Physical and Chemical Reference Data 20, 1023 (1991).

real(c_real), parameter :: triple_point_h2o = 273.16_c_real
! Water_vapor_gas
!	 units: J/kg/K
!	 source info:
!		 definition: r_gas / molec_weight_h2o

real(c_real), parameter :: rgas_h2o_vapor = 461.522_c_real
end module
