/* This file was generated by EKAT with generate_constants.hpp and
 * generate_constants.cpp using data defined in 
 *         ekat/src/ekat/physics/constants.yaml 
 * 
 *      DO NOT EDIT
 * 
*/
#include "ekat/physics/base_constants.hpp"

namespace ekat {
namespace physics {
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_nh3;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_nh4;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::avogadro;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::boltzmann;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::calendar_day;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_co2;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_co;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::carbon_13_to_12_ratio;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_dry_air;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::rgas_dry_air;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::earth_radius;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::earth_omega;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::density_h2o_ice_0c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::karman;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::latent_heat_evap_0c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::latent_heat_fusion;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::latent_heat_sublimation;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_ch4;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_n2;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_no2;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_o2;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_o3;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::pi;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::sidereal_day;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::cp_dry_air;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::cv_dry_air;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::cp_h2o_ice;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::cp_h2o_liq_0c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::cp_h2o_vapor;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::gravity;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::standard_pressure;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::stefan_boltzmann;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_so4;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_h2so4;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::surface_tension_h2o_air_0c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::thermal_conductivity_h2o_ice_0c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::std_pressure;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::r_gas;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::vsmow_ratio_2h_h;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::vsmow_ratio_17o_16o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::vsmow_ratio_18o_16o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::critical_temp_h2o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::density_h2o_liq_0c;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::freezing_pt_h2o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::molec_weight_h2o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::triple_point_h2o;
  template <typename Scalar>
  Scalar constexpr BaseConstants<Scalar>::rgas_h2o_vapor;
// ETI
template struct BaseConstants<float>;
template struct BaseConstants<double>;
} // namespace physics
} // namespace ekat
