# Settings used when Cuda is the Kokkos backend

set(KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION FALSE CACHE BOOL "")
set(KOKKOS_ENABLE_CUDA TRUE CACHE BOOL "")
set(KOKKOS_ENABLE_CUDA_LAMBDA TRUE CACHE BOOL "")
