include (${CMAKE_CURRENT_LIST_DIR}/generic.cmake)

option(Kokkos_ARCH_INTEL_GEN "" ON)
set(Kokkos_ENABLE_DEPRECATED_CODE_3 TRUE CACHE BOOL "")
set(KOKKOS_IMPL_SYCL_DEVICE_GLOBAL_SUPPORTED "0" CACHE STRING "")




