# Settings used when Serial is the Kokkos backend

set(KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION TRUE CACHE BOOL "")
set(KOKKOS_ENABLE_OPENMP FALSE CACHE BOOL "")
set(KOKKOS_ENABLE_SERIAL TRUE CACHE BOOL "")
